services:
  intranet-db:
    image: postgres:16.2-alpine
    container_name: intranet-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ù1nt24N3tù
      - POSTGRES_DB=intranet
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_wal_size=4GB"]