services:
  intranet-db:
    image: postgres:16.2-alpine
    container_name: adr-db
    environment:
      - POSTGRES_USER=moi
      - POSTGRES_PASSWORD=ADR
      - POSTGRES_DB=adr
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_wal_size=4GB"]